### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by thundergolfer** [tomroy/mdtable2csv#1]
Hey, 

You have the `usage` instructions but could you add `installation` instructions to make it immediately obvious how to get started. 

Cheers

**Comment by tomroy** [comment]
@thundergolfer Thank you for your advice, I added a `Prerequisites` section in the README.md.
Hope it can make it easier for users to get started.

**Comment by thundergolfer** [comment]
@tomroy cheers mate.

**Comment by thundergolfer** [comment]
@tomroy I attempted to run mdtable2csv as an application (.exe) on Windows but got an error saying that my 64-bit architecture was incompatible. 

Is this supposed to work on Windows? Have I just gone about it all wrong?

**Comment by tomroy** [comment]
Sorry that I only have MacBook, so I only know how to run it on Mac system, however, I found a video that shows you how to run python on Windows.
https://www.youtube.com/watch?v=E20nhheus4Y
Hope this will help, cheers.
