### ISSUE TITLE
Python 3 support   File "mdtable2csv.py", line 103, in <module>     write_td_to_file += (td.string+',') TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by sergejkaiser** [tomroy/mdtable2csv#2]
Hey,
thanks for the great work. I just tried to run your code on a markdown table with pyhton 3. 
However, I ran into the following probelm File "mdtable2csv.py", line 103, in <module>     write_td_to_file += (td.string+',') TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' . 

I tried to convert the following table.

| Trust     |          |         |         |   Low   |  Medium |   High  |    Low vs. High | Medium vs. High |
|-----------|----------|---------|---------|:-------:|:-------:|:-------:|:---------------:|:---------------:|
|           |          |         |         |  0.7217 |  0.4886 | -1.2103 |        1.932    |      1.6989     |
| Education | x Trust  |         |         |         |         |         |                 |                 |
| 1         |          |         |         |  0.0016 | -0.0454 |  0.0438 |       -0.0422   |     -0.0892     |
| 2         |          |         |         |  0.1251 |  0.0046 | -0.1297 |       0.2548    |      0.1343     |
| 3         |          |         |         | -0.1267 |  0.0408 |  0.0859 |      (-0.2126)  |    (-0.0451)    |
| Age       | x Trust  |         |         |         |         |         |                 |                 |
| 1         |          |         |         | -0.2959 |  0.1887 |  0.1071 |       -0.403    |      0.0816     |
| 2         |          |         |         |  0.2755 | -0.1994 |  -0.076 |       0.3515    |     -0.1234     |
| 3         |          |         |         |  0.0204 |  0.0107 | -0.0311 |      (0.0515)   |     (0.0418)    |
| Gender    | x Trust  |         |         |         |         |         |                 |                 |
| 1         |          |         |         | -0.0089 | -0.0335 |  0.0424 |       -0.0513   |     -0.0759     |
| 2         |          |         |         |  0.0089 |  0.0335 | -0.0424 |      (0.0513)   |     (0.0759)    |
| Vote      | x Trust  |         |         |         |         |         |                 |                 |
| 1         |          |         |         | -0.1512 |  0.0744 |  0.0767 |       -0.2279   |     -0.0023     |
| 2         |          |         |         |  0.1512 | -0.0744 | -0.0767 |      (0.2279 )  |     (0.0023)    |
| Education | X Age    | x Trust |         |         |         |         |                 |                 |
| 1         | 1        |         |         | -0.1164 |  0.163  | -0.0465 |       -0.0699   |      0.2095     |
| 1         | 2        |         |         |  0.2027 | -0.3183 |  0.1156 |       0.0871    |     -0.4339     |
| 1         | 3        |         |         | -0.0862 |  0.1553 | -0.0691 |      (-0.0171)  |     (0.2244)    |
| 2         | 1        |         |         |  0.1335 | -0.1275 | -0.0061 |       0.1396    |     -0.1214     |
| 2         | 2        |         |         | -0.1171 |  0.1397 | -0.0226 |       -0.0945   |     (0.1623)    |
| 2         | 3        |         |         | -0.0165 | -0.0122 |  0.0287 |      (-0.0452)  |    (-0.0409)    |
| 3         | 1        |         |         | -0.0171 | -0.0355 |  0.0526 |      (-0.0697)  |    (-0.0881)    |
| 3         | 2        |         |         | -0.0856 |  0.1785 |  -0.093 |      (0.0074)   |     (0.2715)    |
| 3         | 3        |         |         |  0.1027 | -0.1431 |  0.0404 |      (0.0623)   |    (-0.1835)    |
| Age       | X Gender | x Trust |         |         |         |         |                 |                 |
| 1         | 1        |         |         |  -0.003 |  0.0188 | -0.0158 |       0.0128    |      0.0346     |
| 1         | 2        |         |         |  0.003  | -0.0188 |  0.0158 |      (-0.0128)  |    (-0.0346)    |
| 2         | 1        |         |         |  0.0231 |  0.0914 | -0.1146 |       0.1377    |      0.206      |
| 2         | 2        |         |         | -0.0231 | -0.0914 |  0.1146 |      (-0.1377)  |     (-0.206)    |
| 3         | 1        |         |         | -0.0201 | -0.1102 |  0.1303 |      (-0.1504)  |    (-0.2405)    |
| 3         | 2        |         |         |  0.0201 |  0.1102 | -0.1303 |      (0.1504)   |     (0.2405)    |
| Age       | X Gender | x Trust |         |         |         |         |                 |                 |
| 1         | 1        |         |         |  0.0968 |  0.0058 | -0.1026 |       0.1994    |      0.1084     |
| 1         | 2        |         |         | -0.0968 | -0.0058 |  0.1026 |       -0.1994   |    (-0.1084)    |
| 2         | 1        |         |         | -0.0296 |  0.0497 | -0.0201 |       -0.0095   |      0.0698     |
| 2         | 2        |         |         |  0.0296 | -0.0497 |  0.0201 |       0.0095    |    (-0.0698)    |
| 3         | 1        |         |         | -0.0672 | -0.0556 |  0.1227 |       -0.1899   |    (-0.1783)    |
| 3         | 2        |         |         |  0.0672 |  0.0556 | -0.1227 |       0.1899    |     (0.1783)    |
| Gender    | X Vote   | x Trust |         |         |         |         |                 |                 |
| 1         | 1        |         |         |  0.0875 |  0.0285 |  -0.116 |       0.2035    |      0.1445     |
| 1         | 2        |         |         | -0.0875 | -0.0285 |  0.116  |      (-0.2035)  |    (-0.1445)    |
| 2         | 1        |         |         | -0.0875 | -0.0285 |  0.116  |       -0.2035   |     -0.1445     |
| 2         | 2        |         |         |  0.0875 |  0.0285 |  -0.116 |      (0.2035)   |     (0.1445     |
| Age       | X Gender | X Vote  | X Trust |         |         |         |                 |                 |
| 1         | 1        | 1       |         |  0.0864 |  0.1045 | -0.1909 |       0.2773    |      0.2954     |
| 1         | 1        | 2       |         | -0.0864 | -0.1045 |  0.1909 |      (-0.2773)  |    (-0.2954)    |
| 1         | 2        | 1       |         | -0.0864 | -0.1045 |  0.1909 |     (-0.2773 )  |    (-0.2954)    |
| 1         | 2        | 2       |         |  0.0864 |  0.1045 | -0.1909 |      (0.2773)   |     (0.2954)    |
| 2         | 1        | 1       |         | -0.0841 | -0.1737 |  0.2578 |       -0.3419   |     -0.4315     |
| 2         | 1        | 2       |         |  0.0841 |  0.1737 | -0.2578 |      (0.3419)   |     (0.4315)    |
| 2         | 2        | 1       |         |  0.0841 |  0.1737 | -0.2578 |      (0.3419)   |     (0.4315)    |
| 2         | 2        | 2       |         | -0.0841 | -0.1737 |  0.2578 |      (-0.3419)  |    (-0.4315)    |
| 3         | 1        | 1       |         | -0.0024 |  0.0693 | -0.0669 |      (0.0645)   |     (0.1362)    |
| 3         | 1        | 2       |         |  0.0024 | -0.0693 |  0.0669 |      (-0.0645)  |    (-0.1362)    |
| 3         | 2        | 1       |         |  0.0024 | -0.0693 |  0.0669 |      (-0.0645)  |    (-0.1362)    |
| 3         | 2        | 2       |         | -0.0024 |  0.0693 | -0.0669 |      (0.0645)   |     (0.1362)    |

**Comment by tomroy** [comment]
@sergejkaiser thanks for reporting this problem, this is caused when td.string is None.
I fixed it in the latest commit f316278706b885f33138c4f69456c5ea0009bfc2.

Thank you. 👍 

If it still doesn't work please reopen this issue.
