### ISSUE TITLE
Prerequisite

### ISSUE THREAD

**Issue by ericdost** [tomroy/mdtable2csv#3]
Hello -

I received the following error when attempting to run this for the first time:

```
Traceback (most recent call last):
  File "../../../../mdtable2csv/mdtable2csv", line 7, in <module>
    from flask import abort, json
ImportError: No module named flask
```

I was able to fix this by running:

`pip install flask`

**Comment by tomroy** [comment]
Thanks @ericdost , I'll add this to the Readme file.
