### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by jesnstevens** [tomroy/mdtable2csv#5]
@tomroy, 

Thanks for creating this tool. I'm running macOS Sierra 10.12.5 and I had no trouble installing the prerequisites for this command line tool. But when I follow the next step in your directions which is to use the following command I get ```-bash: mdtable2csv: command not found```. What am I missing? 

Thanks,
@jesnstevens

**Comment by tomroy** [comment]
Hi @jesnstevens 

try to use
```bash
$ ./mdtable2csv filename.md
``` 
under the directory `mdtable2csv`

or

run this command first to assign execute permission to a file
```bash
$ chmod a+x mdtable2csv
```
and then run
```bash
$ ./mdtable2csv filename.md
``` 

I'm glad I can help, if you still have any question, please let me know.
