### ISSUE TITLE
The shebang is not portable across different operating systems

### ISSUE THREAD

**Issue by microngust** [tomroy/mdtable2csv#7]
I had to change the shebang (locally) to the following because the python3 command is in a different directory on Ubuntu 18.04:

#!/usr/bin/env python3

**Comment by aaronmarkham** [comment]
Same here... on MacOs though (with Python 3.7)

**Comment by tomroy** [comment]
fixed in commit 0922178c2aedbdbbd3dbf1109abaa6461064080b
